[tool.poetry]
name = "geodataviz"
version = "0.1.0"
description = ""
authors = ["Omar Roland Baumg√§rtner"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
